#!/usr/bin/env python3

""" Fichier d'entrée du projet.
Usage: ./rapace <topology-file>
	topology-file
		Fichier yaml de configuration de la topologie logique du réseau. 
		Contient: Les hotes (leur nom, et leur equipement tournant desssus) et les liens entre les equipements
"""
import sys
import os

from rapace import start, stop

if __name__ == '__main__':

	# On vérifie qu'il y a bien 2 arguments
	if len(sys.argv) != 2:
		print("ERROR: Usage: ./rapace.py <topology-file>")
		sys.exit(1)
	topology_file = sys.argv[1]

	# On vérifie que c'est bien run avec les droits root
	if not hasattr(os, 'geteuid') or os.geteuid() != 0:
		print("ERROR: Ce script doit etre execute avec les droits root")
		sys.exit(1)

	# On démarre le réseau
	start(topology_file)
	print("INFO: Reseau demarre !")

	# On attend que l'utilisateur appuie sur entrée pour quitter
	input("Appuyez sur entree pour quitter...")

	# On stoppe le réseau
	stop()
	print("INFO: Reseau stoppe !")
