#!/usr/bin/env python3

""" Fichier d'entrée du projet.
Usage: ./rapace <topology-file>
	topology-file
		Fichier yaml de configuration de la topologie logique du réseau. 
		Contient: Les hotes (leur nom, et leur equipement tournant desssus) et les liens entre les equipements
"""
import sys
import os

from rapace import *
from rapace.prompt import *

if __name__ == '__main__':

	# On vérifie qu'il y a bien 2 arguments
	if len(sys.argv) != 2:
		log(ERROR, "Usage: ./rapace.py <topology-file>")
		sys.exit(1)
	topology_file = sys.argv[1]

	# On vérifie que c'est bien run avec les droits root
	if not hasattr(os, 'geteuid') or os.geteuid() != 0:
		log(ERROR, "Ce script doit etre execute avec les droits root")
		sys.exit(1)

	# On démarre le réseau
	try:
		start(topology_file)
		pass
	except KeyboardInterrupt:
		print("")
		log(INFO, "Bye !")
		sys.exit(0)
	except Exception as e:
		log(ERROR, f"Erreur lors du demarrage du reseau : {e}")
		stop()
		sys.exit(1)
	

	# On lance la boucle principale
	try:
		prompt()
	except KeyboardInterrupt or EOFError:
		pass
	print("")
	log(INFO, "Bye !")

	# On stoppe le réseau
	stop()
